call plug#begin()

Plug 'morhetz/gruvbox'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

set encoding=utf-8
filetype plugin indent on
syntax on
set backspace=indent,eol,start
set number
set background=dark
set termguicolors
set t_Co=256
colorscheme gruvbox

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set nobackup
set nowritebackup

set updatetime=300

"set list
"set listchars=tab:>_,eol:¬

set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set expandtab
set smartindent
set hidden

" Mapping
let mapleader = ","
nnoremap <leader>f gg=G
inoremap <leader>f :<ESC>gg=G

inoremap jj <ESC>


" **************** COC.VIM *********************
" Use tab for trigger completion with characters ahead and navigate
" NOTE: There's always complete item selected by default, you may want to enable
" no select by `"suggest.noselect": true` in your configuration file
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

